version: '3.1'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=myfilms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - database-data:/var/lib/postgresql/data/
      
volumes:
  database-data: